version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - agentraVolume:/data/db
    networks:
      - agentraNetwork
  agentra_backend:
    image: 1thenameisshivam/agentra:latest
    container_name: agentra_backend
    depends_on:
      - mongodb
      - inngest
    ports:
      - "3000:3000"
    restart: always
    networks:
      - agentraNetwork
    env_file: .env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/agentra
      - INNGEST_DEV=1
      - INNGEST_BASE_URL=http://inngest:8288
  inngest:
    image: inngest/inngest:v0.27.0
    container_name: inngest
    command: "inngest dev -u http://agentra_backend:3000/api/inngest"
    restart: always
    networks:
      - agentraNetwork
    ports:
      - "8288:8288"
volumes:
  agentraVolume:
networks:
  agentraNetwork:
