name: CI/CD Pipeline Agentra

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NODE_ENV: test
      CI: true

    steps:
      # Step 1: Checkout code
      - name: Checkout repo
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Create .env.test file
      - name: Create .env.test
        run: echo "${{ secrets.ENV_TEST }}" > .env.test

      # Step 5: Run tests
      - name: Run tests
        run: NODE_ENV=test npm test

      # Step 6: Docker build
      - name: Build Docker image
        run: docker build -t 1thenameisshivam/agentra:latest .

      # Step 7: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 8: Push Docker image
      - name: Push image to Docker Hub
        run: docker push 1thenameisshivam/agentra:latest

      # Step 9: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.AZURE_HOST }}
          username: ${{ secrets.AZURE_USER }}
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          script: |
            cd ~/Ai-ticketing-agent
            git pull origin main
            docker compose pull
            docker compose up -d
